GET http://localhost:3000/
####
GET http://localhost:3000/user
####
POST http://localhost:3000/user
Content-Type: application/json

{
    "name":"Luisa",
    "surname": "Marrone",
    "email": "luisamarrone@gmail.com",
    "password":"castagna111"
}